*&---------------------------------------------------------------------*
*& Include          ZRFI_CUST_OPEN_DETAILS_SS
*&---------------------------------------------------------------------*

SELECTION-SCREEN:BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-002.
  SELECT-OPTIONS:s_belnr FOR acdoca-belnr.
  PARAMETERS:p_bukrs TYPE acdoca-rbukrs,
             p_gjahr TYPE acdoca-gjahr.
SELECTION-SCREEN:END OF BLOCK b1.

SELECTION-SCREEN:BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-003.
  PARAMETERS:p_class AS CHECKBOX.
  PARAMETERS:rb_rad1 RADIOBUTTON GROUP rep USER-COMMAND cmd,
             rb_rad2 RADIOBUTTON GROUP rep DEFAULT 'X'.
SELECTION-SCREEN:END OF BLOCK b2.

SELECTION-SCREEN:BEGIN OF BLOCK b3 WITH FRAME TITLE TEXT-004.
  SELECTION-SCREEN:BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(10) TEXT-001 MODIF ID brc.
    PARAMETERS: p_brac_1 TYPE n LENGTH 3 MODIF ID brc.
    SELECTION-SCREEN POSITION 18.
    PARAMETERS: p_brac_2 TYPE n LENGTH 3 MODIF ID brc.
    SELECTION-SCREEN POSITION 25.
    PARAMETERS: p_brac_3 TYPE n LENGTH 3 MODIF ID brc.
  SELECTION-SCREEN:END OF LINE.
SELECTION-SCREEN:END OF BLOCK b3.
